version: 0.2
phases:
  
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - apt update
      - npm install -g serverless
      - npm install serverless-glue
      - sudo apt install python3
      - pip3 install nbconvert

  convert_notebooks:
    commands:
      - jupyter nbconvert --to python ./jobs/*/*.ipynb
      
  build:
    commands:
      - sls deploy