version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - apt update
      - npm install -g serverless
      - npm install serverless-glue
  build:
    commands:
      - sls deploy