service: jobs

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1

plugins:
  - serverless-glue

Glue:
  bucketDeploy: aws-glue-jobs-dummy-cicd
  jobs:
    - ${file(jobs/dummy_job/definition.yml)}
    - ${file(jobs/dummy_job_2/definition.yml)}

