service: jobs

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.7

plugins:
  - serverless-glue

Glue:
  bucketDeploy: aws-glue-jobs
  jobs:
    - ${file(jobs/dummy_job/definition.yml)}

